image: php:7.4-cli

stages:
  - test

before_script:
  - apt-get update
  - bash ci/docker_install.sh > /dev/null

test:
  script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
    - phpunit --configuration phpunit.xml