image: php:7.4-cli

before_script:
  - apt-get update
  - apt-get install zip unzip
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - bash ci/docker_install.sh > /dev/null

test:app:
  script:
    - composer install
    - phpunit --configuration phpunit.xml