image: php:7.4-cli

stages:
  - unit-tests

before_script:
  - apt-get update
  - apt-get install zip unzip
  - bash ci/docker_install.sh > /dev/null

unit-tests:
  script:
    - phpunit --configuration phpunit.xml




