image: php:7.4-cli

stages:
  - test

before_script:
  - apt-get update
  - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-9.4.1.phar
  - chmod +x /usr/local/bin/phpunit
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install

test:
  script:
    - phpunit --configuration phpunit.xml