variables:
  MYSQL_ROOT_PASSWORD: "root_pass"
  MYSQL_USER: "root"
  MYSQL_HOST: mysql

stages:
  - functest
  - test

unit tests:
  stage: test
  image: php:7.4
  script:
    - apt-get update
    - bash ci/docker_install.sh > /dev/null
    - curl --location --output /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-9.4.1.phar
    - chmod +x /usr/local/bin/phpunit
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
    - phpunit --configuration phpunit.xml


functional testing match:
  stage: functest
  image: php:7.4
  services:
    - name: mysql:5.7
      alias: mysql
  before_script:
    - apt update -qy && apt-get install -qqy --no-install-recommends default-mysql-client
    - mysql --user=$MYSQL_USER --password=$MYSQL_ROOT_PASSWORD --host=$MYSQL_HOST < functional_testing/db_setup/db_init.sql
    - mysql --user=$MYSQL_USER --password=$MYSQL_ROOT_PASSWORD --host=$MYSQL_HOST --execute="SHOW DATABASES;"
    - docker-php-ext-install mysqli && docker-php-ext-enable mysqli
  script:
    - cd src
    - php starter.php
    - php starter.php > scriptResult.log
    - sleep 2
    - ls -al
    - cat scriptResult.log


